#attentive configuration file for experiment in PyCIGAR
#inspired by https://github.com/beyretb/AnimalAI-Olympics/blob/master/documentation/configFile.md
#https://github.com/beyretb/AnimalAI-Olympics/blob/master/examples/configs/7-InternalMemory.yaml


#time_step_of_hack = 200



env_config:
  'clip_actions': True
  'sims_per_step': 1

simulation_config:
  network_model_directory: 'feeder34_test.dss'
  custom_configs:  {solution_mode: 1,
                    solution_number: 1,
                    solution_step_size: 1,
                    solution_control_mode: -1,
                    solution_max_control_iterations: 1000000,
                    solution_max_iterations: 30000,
                    power_factor: 0.9}

scenario_config:
  network_data_directory: 'testpvnum10'
  t: 1441
  start_end_time: (37200, 39200)
  custom_configs: {load_scaling_factor: 1.5,
                   generation_scaling_factor: 3,
                   slack_bus_voltage: 1.04,
                   load_generation_noise: False,
                   power_factor: 0.9}

  nodes:
      - name: dl_82034
        load_profile: node_22_pv_10_minute
        devices:
            - name: pv_1
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0]

      - name: dl_858m
        load_profile: node_8_pv_10_minute
        devices:
            - name: pv_2
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0]

      - name: dload_806m
        load_profile: node_25_pv_10_minute
        devices:
            - name: pv_3
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0]

      - name: dload_810
        load_profile: node_4_pv_10_minute
        devices:
            - name: pv_4
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0]

      - name: dload_810m
        load_profile: node_35_pv_10_minute
        devices:
            - name: pv_5
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0]

      - name: dload_822
        load_profile: node_11_pv_10_minute
        devices:
            - name: pv_6
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0]

      - name: dload_822m
        load_profile: node_13_pv_10_minute
        devices:
            - name: pv_7
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0]

      - name: dload_824
        load_profile: node_33_pv_10_minute
        devices:
            - name: pv_8
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0.5]

      - name: dload_826
        load_profile: node_10_pv_10_minute
        devices:
            - name: pv_9
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0]

      - name: dload_826m
        load_profile: node_14_pv_10_minute
        devices:
            - name: pv_10
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0]

      - name: dload_828
        load_profile: node_30_pv_10_minute
        devices:
            - name: pv_11
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0.5]

      - name: dload_830
        load_profile: node_29_pv_10_minute
        devices:
            - name: pv_12
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0.5]

      - name: dload_830m
        load_profile: node_20_pv_10_minute
        devices:
            - name: pv_13
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0.5]

      - name: dload_834
        load_profile: node_5_pv_10_minute
        devices:
            - name: pv_14
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0.5]

      - name: dload_836
        load_profile: node_7_pv_10_minute
        devices:
            - name: pv_15
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0.5]

      - name: dload_838
        load_profile: node_28_pv_10_minute
        devices:
            - name: pv_16
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0]

      - name: dload_838m
        load_profile: node_1_pv_10_minute
        devices:
            - name: pv_17
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0]

      - name: dload_840
        load_profile: node_15_pv_10_minute
        devices:
            - name: pv_18
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0.5]

      - name: dload_844
        load_profile: node_36_pv_10_minute
        devices:
            - name: pv_19
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0]

      - name: dload_846
        load_profile: node_21_pv_10_minute
        devices:
            - name: pv_20
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0]

      - name: dload_848
        load_profile: node_26_pv_10_minute
        devices:
            - name: pv_21
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0]

      - name: dload_856
        load_profile: node_18_pv_10_minute
        devices:
            - name: pv_22
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0]

      - name: dload_856m
        load_profile: node_16_pv_10_minute
        devices:
            - name: pv_23
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0]

      - name: dload_860
        load_profile: node_9_pv_10_minute
        devices:
            - name: pv_24
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0]

      - name: dload_864
        load_profile: node_31_pv_10_minute
        devices:
            - name: pv_25
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0]

      - name: dload_864m
        load_profile: node_19_pv_10_minute
        devices:
            - name: pv_26
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0]

      - name: sload_840
        load_profile: node_37_pv_10_minute
        devices:
            - name: pv_27
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0]


      - name: sload_844
        load_profile: node_3_pv_10_minute
        devices:
            - name: pv_28
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0]

      - name: sload_848
        load_profile: node_34_pv_10_minute
        devices:
            - name: pv_29
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0]

      - name: sload_860
        load_profile: node_27_pv_10_minute
        devices:
            - name: pv_30
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0]

      - name: sload_890
        load_profile: node_17_pv_10_minute
        devices:
            - name: pv_31
              type: pv_device
              controller: adaptive_inverter_controller
              custom_configs: {default_control_setting: [0.98, 1.01, 1.01, 1.04, 1.08],
                               delay_timer: 60}
              adversary_controller: fixed_controller
              adversary_custom_configs: {default_control_setting: [1.014, 1.015, 1.015, 1.016, 1.017]}
              hack: [200, 0]
