% Author : Shammya Saha (sssaha@lbl.gov)
% This function demonstrates the regulator and capacitor control of MATLAB.  
clc;
close all;
clear
%% OpenDSS integration

[DSSObj, DSSText, gridpvpath] = DSSStartup;
% Load the components related to OpenDSS
DSSCircuit=DSSObj.ActiveCircuit;
DSSSolution=DSSCircuit.Solution;

%Compile the Model, Directory of the OpenDSS file, Please find the associated Feeder 
% And Make sure you have the appropriate directory
DSSText.command = 'Compile feeder13_U_R_Pecan.dss';
% DSSText.command ='set controlmode=ON';
%Changing the Max tap just to make sure this info can be retrieved later
% DSSText.Command='RegControl.lvr-lvr_01.maxtapchange=16' ;
setRegInfo(DSSObj,[{'lvr-lvr_01'}],'maxtapchange',[16]);
setCapInfo(DSSObj,[{'cap_675'}],'kvar',[600]);
%% Solving the power flow in QSTS mode
% DSSSolution.ControlMode=0;
DSSSolution.Mode=1; % 1 represents daily mode
DSSSolution.Number=1440; % Solutions Per Solve Command
DSSSolution.StepSize=1; % Stepsize= 1s
DSSSolution.MaxControlIterations=1000; % Increase the number of maximum control iterations to make sure the system can solve the power flow
DSSSolution.MaxIterations=100;
DSSSolution.ControlMode=2; % For Controlmode= Time
%  Or Alternatively use this 
% setSolutionParams(DSSObj,'daily',1440,1,'time',1000,100);
DSSSolution.Solve();




%% Getting the Regulator Info
regs=getRegInfo(DSSObj);
fprintf('MaxTapChange: %d\n', regs.MaxTapChange);


%% Getting Capacitor Info
caps=getCapacitorInfo(DSSObj);
fprintf('Caps KVAR Value: %f\n',caps.kvar);
fprintf('Caps PTratio Value: %f\n',caps.PTratio);

%% Setting Capacitor Control Info, for example setting the off setting
setCapControlInfo(DSSObj,[{'capc_611'},{'capc_675'}],'offsetting',[1.01,1.01]);

%% Get all the Monitors
DSSMon=DSSCircuit.Monitors;
% Set this one as the active monitor
DSSMon.Name='meter_675';
% print the monitor name
fprintf('Monitor Name: %s\n',DSSMon.Name);
Headers=DSSMon.Header;
fprintf('Header Name: %s\n',Headers{:} );
% Getting the value in pu, 2400 is the base value of that bus
Vrms = ExtractMonitorData(DSSMon,1,2400);
time=ExtractMonitorData(DSSMon,0,1);
plot(time,Vrms,'linewidth',1.5);
xlabel('Time')
xlim([1 length(time)]);
ylabel('Voltage (pu)')
title ('Voltage Recorded at Meter 634');

% Getting the total reactive power from the capacitor at bus 675
DSSMon.Name='VAR_Meter_675';
fprintf('\nMonitor Name: %s\n',DSSMon.Name);
Headers=DSSMon.Header;
fprintf('Header Name: %s\n',Headers{:} );
% Qvar = ExtractMonitorData(DSSMon,2,1);
Qvar = ExtractMonitorData(DSSMon,2,1)+ExtractMonitorData(DSSMon,4,1)+ExtractMonitorData(DSSMon,6,1);
figure
% negative Value as generation is negative by default in OpenDSS
plot(time,-Qvar,'linewidth',1.5);
xlim([1 length(time)]);
title('VAR generated by Capacitor')



