class KernelSimulation(object):
    """Base simulation kernel.

    This kernel subclass is responsible for start/restart the simulator,
    run a simulator 1 step.
    """

    def __init__(self, master_kernel):
        """Instantiate the base simulation kernel.

        Parameters
        ----------
        master_kernel : pycigar.core.kernel.Kernel
            The highest level kernel (used to call methods from other
            sub-kernels)
        """
        self.master_kernel = master_kernel
        self.kernel_api = None

    def pass_api(self, kernel_api):
        """Accquire the kernel api that was generated by the simulation kernel.

        Parameters
        ----------
        kernel_api : any
            an API that is used to interact with the simulator.
        """
        self.kernel_api = kernel_api

    def start_simulation(self, sim_params):
        """Start the simulator and return the API to interact with the simulator.

        This is also responsible for creating new simulator process since
        Gridlab-D and OMF run on Python 2.7 and interacting through a
        TCP/IP connection.
        For OpenDSS, we try to open a new process and use TCP/IP connection,
        but it is too slow. Therefore, we decide to create a pseudo API which
        call the methods of OpenDSS.

        Parameters
        ----------
        sim_params : dict
            The simulation parameters, including simulation configs.
        """
        raise NotImplementedError

    def update(self, reset):
        """Call the simulator to run 1 simulation step.

        Parameters
        ----------
        reset : bool
            specifies whether the simulator was reset in the last simulation
            step.
        """
        raise NotImplementedError

    def check_converged(self):
        """Check the convergence after run the simulator 1 simulation step."""
        raise NotImplementedError

    def close(self):
        """Close the simulator process (if opened with subprocess.popen())."""
        raise NotImplementedError
